import { Col, Row } from 'antd';
import React from 'react'
import styled, { withTheme } from "styled-components";
import { maxWidth } from '../helper';

const Container = styled.section`
    width: 100%;
    max-width: ${maxWidth};
    margin: 100px auto 0px auto;
    padding: 100px 0px;  
    box-sizing: border-box;
    text-transform: uppercase;
    text-align: justify;

    @media (max-width: ${maxWidth}){
        padding: 60px 20px;
    }

    h2, h3, h1 {
        font-weight: bold;
    }

    p, h3 {
        font-size: 16px;
        text-align: justify;
    }

    span {
        font-weight: 900;
    }
`;


function Conditions() {
    return (
        <Container>
            <Row gutter={16}>
                <Col xs={24} md={12}>
                    <h1>TERMOS E CONDIÇÕES</h1>
                    <p><span>1. OBJETO -</span> 1.1 - O presente contrato é celebrado entre CR Rent (adiante designado por Locadora), o cliente e os condutores identificados no mesmo (adiante designados por Locatário). Através do presente contrato a locadora aluga o veículo automóvel ao Locatário, nos seguintes termos e condições gerais, sobre as quais toma conhecimento e concorda:</p>
                    <p><span>2. ENTREGA E DEVOLUÇÃO DO VEÍCULO -</span> 2.1 O Locatário declara que recebeu o veículo nas devidas condições de utilização e limpeza, com os respetivos acessórios, ferramentas e documentos do veículo, comprometendo-se a devolvê-lo nas mesmas condições em que o recebeu, no local e data designados no contrato. - 2.2 - Caso o veículo seja utilizado em violação do contrato, a Locadora pode resolver o contrato, sendo obrigatória a devolução do veículo pelo Locatário no local indicado, sob pena de o veículo lhe ser retirado, nos termos da lei, às expensas deste. -2.3-Se o Locatário desejar prolongar o período de aluguer deve dirigir-se às instalações da locadora para celebrar novo contrato, sujeito a aprovação. -2.4-O período mínimo de aluguer é de 1 dia (24h). Em caso de atraso superior a 1 hora serão cobrados 1 dia de aluguer extra. -2.5 - A Locadora não é responsável perante o Locatário ou qualquer passageiro pela perda ou por danos materiais a quaisquer objetos deixados no veículo, quer durante o período de aluguer, quer após o mesmo.</p>
                    <p><span>3. UTILIZAÇÃO DO VEÍCULO -</span>3.1 - O locatário deve cuidar do veículo, assegurando-se que o mesmo fica devidamente fechado à chave e em local seguro quando não esteja a ser utilizado.  - 3.2-O Locatário deverá abastecer o veículo com o tipo de combustível adequado ao mesmo. - 3.3 - O locatário compromete-se a não utilizar ou a não permitir o uso do veículo nas seguintes situações: a) Para efetuar transporte de passageiros ou mercadorias em violação da lei; b) Para transporte de mercadorias ou passageiros a troco de qualquer remuneração ou compensação implícita ou explícita; c) Para rebocar e/ou impulsionar qualquer veículo, reboque ou outro objeto; d) Para provas desportivas; e) Por qualquer pessoa sob influência de álcool, substâncias psicotrópicas ou quaisquer outras que perturbem a capacidade de condução; f) Por pessoas detentoras de carta de condução há menos de um ano, e por pessoas que não estejam identificadas no contrato;  - 3.4-É vedado ao Locatário fumar no interior do veículo, sendo que a verificação de tal indícios determinam o pagamento por parte do Locatário de uma penalização no valor de 100€ para a devida limpeza.</p>
                    <p><span>4. manutenção E reparação DO veículo -</span>NO CASO DE O VEíCULO SOFRER ALGUMA AVARIA, AS REPARAçõesS SO PODEM SER EFETUADAS MEDIANTE ACORDO PRéVIO COM A LOCADORA</p>
                    <p><span>5. reponsabilidades do locatário -</span>Serão da responsabilidade e conta do Locatário: a) Todas as despesas incorridas durante o período do aluguer, designadamente combustível, estacionamento e portagens; b) Multas, coimas e todas e quaisquer infrações inerentes à utilização e condução do veículo, bem como pelas respetivas despesas judiciais e encargos com a identificação de condutores e/ou tratamento dos processos, estipulando-se esses encargos no valor de 35€ a título de despesas administrativas; c) Todos os custos decorrentes de reparação e danos no veículo que o Locatário tiver causado por condução perigosa ou negligente, condução em violação de qualquer norma do Código da Estrada; d) Todos os custos de reparação do veículo devido a choque, colisão, capotamento, incêndio, atos de vandalismo e/ou roubo do veículo, que não excedam a responsabilidade máxima mencionada no contrato (Franquia), salvo se os mesmos forem recuperáveis pela responsabilização de terceiros; e) O custo referente ao serviço de abastecimento do veículo no valor de 25€ e do combustível em falta, caso o mesmo seja devolvido com menor quantidade do que o descrito no documento de entrega; f) Os custos suportados pela Locadora decorrentes da remoção de combustível inadequado no veículo, e da eventual reparação de danos causados com tal abastecimento; g) Os custos de emissão de segundas vias dos documentos do veículo, no caso de extravio ou perda dos originais pelo Locatário, no valor de 150€ a título de despesas administrativas. h) Os custos da substituição dos pneus danificados decorrentes da utilização anormal do veículo; i) O valor devido pela prestação do serviço de devolução da viatura, no caso de o Locatário entregar o veículo em local diferente do previsto, de acordo com o preçário em vigor; j) Todas as despesas judiciais e extrajudiciais, multas e outras sanções pecuniárias, qualquer que seja a sua natureza, decorrentes da violação de qualquer norma imputável ao Locatário ou ao veículo enquanto na posse do mesmo, salvo se tal resultar por responsabilidade da Locadora</p>
                    <p><span>6. serviços -</span>6.1 - O locatário pode contratar os seguintes serviços, cujos valores estão disponíveis para consulta e afixados no estabelecimento e na página web: a) CDW -Abrange todos os danos causados na viatura em caso de acidente, estando o locatário sujeito ao pagamento de uma franquia variável em função do tipo de veículo e de acordo com os valores indicados no presente contrato; b) SCDW  -  Abrange todos os danos causados na viatura e roubo total ou parcial da mesma, não estando o locatário sujeito ao pagamento de qualquer franquia; c) PAI  -  Abrange Acidentes pessoais do condutor, cujo montantes máximos são de 1.000€ no caso despesas medicas ou internamento e de 10.000€ no caso de morte ou invalidez;  - 6.2 - O locatário obriga-se, em caso de acidente, a ter os seguintes procedimentos: a) Participar à locadora e às autoridades policiais todo e qualquer acidente, furto, roubo ou quaisquer outros sinistros, no prazo máximo de 24 horas; b) Obter os nomes e endereços das pessoas envolvidas e de eventuais testemunhas; c) Não abandonar o veículo sem tomar as medidas adequadas com vista à proteção e salvaguarda do mesmo; d) Não assumir qualquer responsabilidade ou declarar-se culpado no caso de acidentes que possam implicar responsabilidade da locadora; e) Contactar imediatamente a locadora fornecendo-lhe um relatório detalhado do acidente incluindo auto de acidente levantado pelas autoridades policiais; f) Se, por motivos de força maior, não for possível proceder de acordo com o indicado nas alíneas anteriores da cláusula 6.2, tais medidas deverão ser tomadas assim que seja possível ao locatário.  - 6.3 - Apenas o locatário e/ou os condutores autorizados podem beneficiar das coberturas CDW, SCDW e PAI.  - 6.4-Mesmo no caso de o locatário subscrever à cobertura SCDW, todos os danos decorrentes da má utilização do veículo são da sua exclusiva responsabilidade.  - 6.5 - Em caso de acidente devido a conduta negligente, será o locatário responsável pela totalidade das despesas da reparação e indemnização correspondente ao tempo de paralisação do veículo acidentado, mesmo que tenha sido contratada a cobertura SCDW e/ou CDW.  - 6.6  -  O veículo apenas terá a cobertura CDW e/ou SCDW durante o período acordado no contrato, exceto se houver prolongamento do contrato nos termos das presentes condições gerais, declinando desde já a locadora toda e qualquer responsabilidade por acidentes ou infrações causadas pelo locatário para além do período de aluguer, sendo este o único e exclusivo responsável pelas mesmas.  - 6.7-A locadora não é responsável por acidentes que não sejam reportados às autoridades policiais. As coberturas CDW e SCDW não cobrem danos causados nos pneus, nos vidros, nas fechaduras, na embraiagem, nem cobrem a perda ou danos às chaves.</p>
                    <p><span>7. pagamentos -</span>7.1 - O locatário obriga-se, expressamente, a pagar as importâncias devidas, e decorrentes da celebração do presente contrato, à locadora logo que lhe sejam solicitadas, nomeadamente: a) O preço devido pelo aluguer do veículo, em função do período de aluguer, calculado de acordo com as tarifas em vigor, o qual está indicado no presente contrato; b) Todos e quaisquer encargos referentes à supressão de franquia cobertura de acidentes pessoais, cobertura de choque, colisão e capotamento, cobertura de roubo e quaisquer outras despesas aplicáveis em conformidade com a tarifa ou taxas constantes no presente contrato; c) Todos os impostos e taxas incidentes sobre o aluguer do veículo ou o montante fixado pela locadora para reembolso desses impostos; d) Todos os custos suportados pela locadora emergentes da cobrança de pagamentos em dívida pelo locatário, em consequência do presente contrato.  - 7.2 - Toda e qualquer fatura não paga na data do vencimento será acrescida de juros de mora à taxa máxima legalmente permitida;  - 7.3 - Em caso de acidente o locatário pagará, a título de despesas administrativas com o respetivo processo, o valor de 50€. - 7.4 - O locatário, para garantia do cumprimento das obrigações decorrentes do Contrato, se não optar pela cobertura SCDW prestará caução, em dinheiro, cheque ou débito em cartão de crédito de acordo com a tabela em vigor, autorizando expressamente a locadora a preencher e a debitar no cartão de crédito as importâncias devidas.</p>
                    <p><span>8. domicílio convencionado -</span>As partes convencionam as moradas indicadas no Contrato para qualquer contacto, nomeadamente, para efeitos de citações ou notificações.</p>
                    <p><span>9. informações e esclarecimentos -</span>O locatário reconhece que todas as cláusulas constantes do presente contrato lhe foram atempadas e expressamente comunicadas e explicadas, e que o mesmo ficou ciente das mesmas, pelo que assina o presente contrato.</p>
                    <p><span>10. dados pessoais -</span>10.1 - O locatário deve fornecer no início do Contrato os seus dados pessoais e os do(s) condutor(es) do veículo, para efeitos da respetiva identificação, autorizando expressamente a locadora a proceder ao tratamento informático dos mesmos. 10.2 - A locadora é a entidade responsável pelo tratamento informático dos dados pessoais fornecidos no âmbito do contrato. 10.3 - Nos termos da Lei n.º 67/98, de 26 de outubro, Lei de Proteção de Dados Pessoais, é garantido às entidades emitentes, respetivos responsáveis e/ou utilizadores nomeados o acesso aos seus dados pessoais para efeitos, nomeadamente, da sua retificação, atualização ou modificação.</p>
                    <p><span>11. execício de direitos -</span> este estabelecimento possui livro de reclamações físico e eletrónico conforme o decreto de lei nº 74/217 de 21 de junho</p>
                </Col>
                <Col xs={24} md={12}>
                    <h1>TERMS AND CONDITIONS</h1>
                    <p><span>1. OBJECT -</span>1.1 - This contract is concluded between CR Rent (hereinafter referred to as the Rental Company), the customer and the drivers identified therein (hereinafter referred to as the Renter). Through this contract the Rental Company rents the car to the Renter, under the following general terms and conditions, about which it takes knowledge and agrees: </p>
                    <p><span>2. DELIVERY AND RETURN OF THE VEHICLE -</span>2.1-The Renter declares that he received the vehicle in proper conditions of use and cleanliness, with the respective accessories, tools and vehicle documents, committing to return it in the same conditions in which he received it, at the place and date designated in the contract.  - 2.2-If the vehicle is used in violation of the contract, the Rental Company may terminate the contract, being mandatory the return of the vehicle by the Renter at the indicated place, under penalty of the vehicle being taken away from him, under the terms of the law, at his expense.  - 2.3-If the Renter wishes to extend the rental period, he must go to the rental company's facilities to celebrate a new contract, subject to approval.  - 2.4-The minimum rental period is 1 day (24h). In case of delay longer than 1 hour, 1 extra day of rental will be charged.  - 2.5-The Rental Company is not liable to the Renter or any passenger for loss or property damage to any objects left in the vehicle, either during or after the rental period. </p>
                    <p><span>3. USE OF THE VEHICLE -</span>3.1-The Renter must take care of the vehicle, ensuring that it is properly locked and in a safe place when not in use.  - 3.2-The Renter must fill up the tank of the vehicle with the type of fuel suitable for it.  - 3.3-The Renter undertakes not to use or allow the use of the vehicle in the following situations: a) To carry passengers or goods in violation of the law; b) To carry goods or passengers in exchange for any implicit or explicit remuneration or compensation; c) To tow and/or propel any vehicle, trailer or other object; d) For sporting events; e) By any person under the influence of alcohol, psychotropic substances or any other substances that disturb driving ability; f) By persons who have held a driving license for less than one year, and by persons who are not identified in the contract;  - 3.4-The Renter is forbidden to smoke inside the vehicle, and the verification of such evidence determines the payment by the Renter of a penalty in the amount of 100€ for proper cleaning.</p>
                    <p><span>4. MAINTENANCE AND REPAIR OF THE VEHICLE -</span>If the vehicle suffers any damage, repairs can only be made by prior agreement with the rental company.</p>
                    <p><span>5. RENTER'S LIABILITIES -</span>The Renter is responsible and liable for: a) All expenses incurred during the rental period, namely fuel, parking and tolls; b) Fines and any and all infractions inherent to the use and driving of the vehicle, as well as for the respective legal costs and charges with the identification of drivers and/or processing of the processes, stipulating these charges in the amount of 35€ as administrative expenses; c) All costs arising from repair and damage to the vehicle that the Renter has caused by dangerous or negligent driving, driving in violation of any rule of the Highway Code; d) All costs of repairing the vehicle due to impact, collision, vehicle rollover, fire, acts of vandalism and/or theft of the vehicle, which do not exceed the maximum liability mentioned in the contract (Excess), unless they are recoverable by the liability of a third party; e) The cost referring to the vehicle refueling service in the amount of €25 and the cost of the missing fuel, if the vehicle is returned with less quantity than described in the delivery document; f) The costs borne by the Rental Company arising from the removal of unsuitable fuel in the vehicle, and the possible repair of damage caused by such refueling; g) The costs of issuing new vehicle’s documents, in the event of loss of the originals by the Renter, in the amount of 150€ as administrative expenses h) The costs of replacing damaged tires resulting from abnormal use of the vehicle; i) The amount due for the provision of the vehicle return service, in case the Renter delivers the vehicle to a location other than the one foreseen, in accordance with the price list in force; j) All judicial and extrajudicial expenses, fines and other pecuniary sanctions, whatever their nature, resulting from the violation of any rule attributable to the Renter or to the vehicle while in the possession of the same, unless this results from the responsibility of the Rental Company;</p>
                    <p><span>6. services -</span>6.1 - The Renter may hire the following services, whose values are available for consultation and posted in the establishment and on the web page: a) CDW - Covers all damages caused to the vehicle in case of accident, being the Renter subject to the payment of a variable deductible depending on the type of vehicle and in accordance with the values indicated in this contract; b) SCDW - Covers all damages caused to the vehicle and total or partial theft of the same, not being the Renter subject to the payment of any deductible; c) PAI - Covers personal accidents to the driver, whose maximum amounts are of 1.000€ in case of medical or hospitalization expenses and of 10.000€ in case of death or invalidity;  - 6.2-The Renter is obliged, in case of accident, to take the following procedures: a) Report to the lessor and to the police authorities any and all accidents, theft, robbery or any other claims, within a maximum period of 24 hours; b) Obtain the names and addresses of the persons involved and any witnesses; c) Not leave the vehicle without taking the appropriate measures with a view to protecting and safeguarding it; d) Not to assume any responsibility or to plead guilty in case of accidents that may imply the responsibility of the Rental Company; e) To immediately contact the Rental Company, providing it with a detailed report of the accident including the accident report drawn up by the police authorities; f) If, for reasons of force majeure, it is not possible to proceed as indicated in the preceding paragraphs of clause 6.2, such measures shall be taken as soon as it is possible for the renter.  - 6.3-Only the Renter and/or authorized drivers may benefit from CDW, SCDW and PAI coverages.  - 6.4-Even in case the Renter subscribes to SCDW coverage, all damages arising from misuse of the vehicle are the Renter's sole responsibility.  - 6.5-In case of an accident due to negligent conduct, the Renter will be responsible for the entire cost of repair and compensation corresponding to the downtime of the accident vehicle, even if SCDW and/or CDW coverage has been subscribed.  - 6.6 - The vehicle will only be covered by CDW and/or SCDW during the period agreed in the contract, except if there is an extension of the contract under the terms of these general conditions, henceforth declining the Rental company any and all responsibility for accidents or infractions caused by the Renter beyond the rental period, being the renter the only and exclusive responsible for them.  - 6.7-The Rental Company is not responsible for accidents that are not reported to the police authorities. CDW and SCDW coverages do not cover damage to tires, glass, locks, clutch, nor do they cover loss or damage to keys.</p>
                    <p><span>7. PAYMENTS -</span>7.1 - The Renter expressly undertakes to pay the amounts due, and arising from the conclusion of this contract to the lessor as soon as they are requested, namely: a a) The price due for the vehicle rental, in accordance with the rental period, calculated according to the rates in force, which is indicated in this contract; b) Any and all charges relating to the suppression of deductibles personal accident cover, crash, collision and roll over cover, theft cover and any other expenses applicable in accordance with the tariff or rates contained in this contract; c) All taxes and charges incurred on the rental of the vehicle or the amount fixed by the Lessor for reimbursement of such taxes; d) All costs supported by the Rental Company arising from the recovery of payments owed by the Renter as a result of this contract.  - 7.2-All and any invoice not paid on the due date shall be increased by default interest at the maximum rate legally allowed;  - 7.3-In case of accident, the Renter shall pay, as administrative fee with the respective process, the amount of 50€.  - 7.4-The Renter, to guarantee the fulfillment of the obligations arising from the Contract, if not opting for SCDW coverage, shall provide deposit, in cash, check or credit card debit, according to the current rates, expressly authorizing the Rental Company to fill in and debit the credit card with the amounts due.</p>
                    <p><span>8. agreed address -</span>The parties agree to use the addresses indicated in the Contract for any contact, namely for the purpose of summons or notifications. </p>
                    <p><span>9. INFORMATION AND CLARIFICATIONS -</span>The Renter acknowledges that all the conditions of this contract have been duly and clearly communicated and explained to him, and that he was aware of them and therefore signs this contract.</p>
                    <p><span>10. PERSONAL DATA -</span>10.1 - The Renter must provide at the beginning of the Contract his personal data and that of the driver(s) of the vehicle, for identification purposes, authorizing the rental company to process them. - 10.2 - The Rental Company is the entity responsible for the computer processing of the personal data provided under the Contract.  - 10.3 - In the terms of Law No. 67/98 of 26 October, the General Data Protection Regulation, it is guaranteed to issuing entities, their responsible and/or named users the access to their personal data for the purposes, namely, its rectification, update or modification.</p>
                    <p><span>11. EXERCISE OF RIGHTS -</span>This establishment has a physical and electronic complaints book in accordance with the Decree-Law No. 74/2017 of the 21st of June.</p>
                </Col>
            </Row>
        </Container>
    )
}

export default Conditions