export const types = {
    FETCH_LOCALIZATIONS: 'FETCH_LOCALIZATIONS',
    UPDATE_LOCALIZATION: 'UPDATE_LOCALIZATION',
    SET_CURRENT_LOCALIZATION: 'SET_CURRENT_LOCALIZATION',
    DELETE_LOCALIZATION: 'DELETE_LOCALIZATION',
    CREATE_LOCALIZATION: 'CREATE_LOCALIZATION'
};