export const types = {
    FETCH_RESERVATIONS: 'FETCH_RESERVATIONS',
    FETCH_RESERVATION: 'FETCH_RESERVATION',
    DELETE_RESERVATION: 'DELETE_RESERVATION',
    UPDATE_RESERVATION: 'UPDATE_RESERVATION',
    CREATE_RESERVATION: 'CREATE_RESERVATION',
    SET_CURRENT_RESERVATION: 'SET_CURRENT_RESERVATION',
    SET_CURRENT_RESERVATION_VALUES: 'SET_CURRENT_RESERVATION_VALUES',
    SET_CURRENT_ERRORS: 'SET_CURRENT_ERRORS',
    CONFIRM_RESERVATION: 'CONFIRM_RESERVATION'
};