export const types = {
    FETCH_AGENCIES: 'FETCH_AGENCIES',
    UPDATE_AGENCY: 'UPDATE_AGENCY',
    SET_CURRENT_AGENCY: 'SET_CURRENT_AGENCY',
    DELETE_AGENCY: 'DELETE_AGENCY',
    CREATE_AGENCY: 'CREATE_AGENCY',
    FETCH_AGENCY: 'FETCH_AGENCY'
};