export const types = {
    FETCH_CARS: 'FETCH_CARS',
    FETCH_CAR: 'FETCH_CAR',
    DELETE_CAR: 'DELETE_CAR',
    UPDATE_CAR: 'UPDATE_CAR',
    CREATE_CAR: 'CREATE_CAR',
    SET_CURRENT_CAR: 'SET_CURRENT_CAR',
    FETCH_CARS_SELECTOR: 'FETCH_CARS_SELECTOR',
    SET_CAR_STATUS: 'SET_CAR_STATUS'
};