export const types = {
    FETCH_CARS: 'FETCH_CARS',
    FETCH_CAR: 'FETCH_CAR',
    DELETE_CAR: 'DELETE_CAR',
    UPDATE_CAR: 'UPDATE_CAR',
    CREATE_CAR: 'CREATE_CAR',
    SET_CURRENT: 'SET_CURRENT',
    FETCH_CARS_SELECTOR: 'FETCH_CARS_SELECTOR'
};