export const types = {
    FETCH_LEVELS: 'FETCH_LEVELS',
    FETCH_LEVEL: 'FETCH_LEVEL',
    DELETE_LEVEL: 'DELETE_LEVEL',
    UPDATE_LEVEL: 'UPDATE_LEVEL',
    CREATE_LEVEL: 'CREATE_LEVEL',
    SET_CURRENT_LEVEL: 'SET_CURRENT_LEVEL',
    FETCH_LEVELS_SELECTOR: 'FETCH_LEVELS_SELECTOR',
    SET_LEVEL_STATUS: 'SET_LEVEL_STATUS',
    FETCH_LEVELS_AVAILABILITY: 'FETCH_LEVELS_AVAILABILITY'
};