export const types = {
    FETCH_COMISSIONS: 'FETCH_COMISSIONS',
    UPDATE_COMISSION: 'UPDATE_COMISSION',
    SET_CURRENT_COMISSION: 'SET_CURRENT_COMISSION',
    DELETE_COMISSION: 'DELETE_COMISSION',
    CREATE_COMISSION: 'CREATE_COMISSION'
};