export const types = {
    FETCH_BLOCKS: 'FETCH_BLOCKS',
    DELETE_BLOCK: 'DELETE_BLOCK',
    CREATE_BLOCK: 'CREATE_BLOCK',
    HAS_BLOCK: 'HAS_BLOCK',
    FETCH_BLOCKS_SELECTOR: 'FETCH_BLOCKS_SELECTOR'
};