export const types = {
    FETCH_PROMOTIONS: 'FETCH_PROMOTIONS',
    FETCH_PROMOTION: 'FETCH_PROMOTION',
    SET_CURRENT_PROMOTION: 'SET_CURRENT_PROMOTION',
    DELETE_PROMOTION: 'DELETE_PROMOTION',
    UPDATE_PROMOTION: 'UPDATE_PROMOTION',
    CREATE_PROMOTION: 'CREATE_PROMOTION',
};